[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'

[[plugins]]
repo = 'gruvbox-community/gruvbox'
hook_add = '''
source ~/.config/nvim/plugins/gruvbox.rc.vim
'''

# [[plugins]]
# repo = 'tjdevries/colorbuddy.vim'

# [[plugins]]
# repo = 'Th3Whit3Wolf/onebuddy'
# depends = 'colorbuddy.vim'
# hook_add = '''
# " source ~/.config/nvim/plugins/onebuddy.rc.vim
# '''

# [[plugins]]
# repo = 'joshdick/onedark.vim'
# hook_add = '''
# " source ~/.config/nvim/plugins/onedark.rc.vim
# '''

# [[plugins]]
# repo = 'cocopon/iceberg.vim'
# hook_add = '''
# source ~/.config/nvim/plugins/iceberg.rc.vim
# '''
