[[plugins]]
repo = 'Shougo/neoinclude.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
source ~/.config/nvim/plugins/deoplate.rc.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = 'deoplete.nvim'
hook_add = '''
source ~/.config/nvim/plugins/neosnippet.rc.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
depends = 'deoplete.nvim'

[[plugins]]
repo = 'thomasfaingnaert/vim-lsp-snippets'
depends = 'vim-lsp'

[[plugins]]
repo = 'thomasfaingnaert/vim-lsp-neosnippet'
depends = 'vim-lsp'

[[plugins]]
repo = 'ujihisa/neco-look'
depends = 'deoplete.nvim'
on_i = 1
hook_add = '''
source ~/.config/nvim/plugins/neco-lock.rc.vim
'''

[[plugins]]
repo = 'lighttiger2505/deoplete-vim-lsp'
depends = 'vim-lsp'
